"""initial3

Revision ID: 77cee402caf8
Revises: abdb312532f0
Create Date: 2025-06-11 00:08:14.002819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77cee402caf8'
down_revision: Union[str, None] = 'abdb312532f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('announce', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_announce'), 'news', ['announce'], unique=False)
    op.create_index(op.f('ix_news_date'), 'news', ['date'], unique=False)
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=False)
    op.create_index(op.f('ix_news_link'), 'news', ['link'], unique=False)
    op.create_index(op.f('ix_news_title'), 'news', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_title'), table_name='news')
    op.drop_index(op.f('ix_news_link'), table_name='news')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_index(op.f('ix_news_date'), table_name='news')
    op.drop_index(op.f('ix_news_announce'), table_name='news')
    op.drop_table('news')
    # ### end Alembic commands ###
