# Use official Python image
FROM python:3.13-slim

# Set working directory
WORKDIR /src

# Install dependencies
COPY back/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY back/ .

# Command to run app
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
