version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: back/DockerFile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./back:/src
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped