version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: back/DockerFile
    container_name: back-container
    ports:
      - "8000:8000"
    volumes:
      - ./back:/src
    env_file:
      - ./back/.env
    restart: unless-stopped