services:
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
    backend:
      build:
        context: .
        dockerfile: back/DockerFile
      container_name: fastapi-backend
      ports:
        - "8000:8000"
      environment:
        - DATABASE_URL=${DATABASE_URL}
      env_file:
        - ./nfac-back-first/back/.env
      command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload